import { SituationTemplate } from '../types';

// Popular templates (인기 템플릿)
export const POPULAR_TEMPLATES = [
  'car_camping',
  'business_trip',
  'hospital_admission',
  'overseas_travel',
  'moving',
  'camping',
  'cherry_blossom_date',
  'korean_bbq',
  'movie_date',
  'wedding_guest',
  'job_interview',
  'remote_work',
  'waterpark',
  'glamping',
  'airport_departure',
  'seollal_homecoming'
];

export const SITUATION_TEMPLATES: SituationTemplate[] = [
  // === 인기 템플릿 ===
  {
    id: 'business_trip',
    name: '출장 준비',
    description: '💼 완벽한 출장을 위한 꿀팁 준비물',
    category: '업무',
    peopleMultiplier: false,
    items: [
      { title: '노트북+충전기', description: '업무용 + 🔥꿀팁: 여분 케이블', baseQuantity: 1, unit: '세트' },
      { title: 'USB/외장하드', description: '🔥꿀팁: 중요파일 백업용', baseQuantity: 1, unit: '개' },
      { title: 'HDMI/VGA케이블', description: '🔥꿀팁: 프레젠테이션용 어댑터', baseQuantity: 1, unit: '세트' },
      { title: '정장/업무복', description: '미팅용 + 🔥꿀팁: 주름방지 포장', baseQuantity: 2, unit: '벌' },
      { title: '와이셔츠', description: '🔥꿀팁: 논아이롱 추천', baseQuantity: 2, unit: '개' },
      { title: '넥타이+벨트', description: '정장 필수 악세사리', baseQuantity: 1, unit: '세트' },
      { title: '구두+구두약', description: '🔥꿀팁: 출장 전날 구두 닦기', baseQuantity: 1, unit: '세트' },
      { title: '양말/속옷', description: '🔥꿀팁: 출장일수 +2일분 여분', baseQuantity: 5, unit: '벌' },
      { title: '잠옷/슬리퍼', description: '🔥꿀팁: 호텔에서 편안하게', baseQuantity: 1, unit: '세트' },
      { title: '명함', description: '여분 넉넉히 + 명함지갑', baseQuantity: 30, unit: '매' },
      { title: '출장 서류', description: '회의자료 + 🔥꿀팁: 클라우드 백업', baseQuantity: 1, unit: '세트' },
      { title: '메모장+펜', description: '🔥꿀팁: 필기용 노트+볼펜 여러개', baseQuantity: 1, unit: '세트' },
      { title: '보조배터리', description: '🔥꿀팁: 20000mAh 이상', baseQuantity: 1, unit: '개' },
      { title: '멀티어댑터', description: '🔥꿀팁: 해외출장 필수', baseQuantity: 1, unit: '개' },
      { title: '세면도구', description: '칫솔+치약+면도기+로션', baseQuantity: 1, unit: '세트' },
      { title: '헤어 스타일링', description: '🔥꿀팁: 왁스+스프레이+빗', baseQuantity: 1, unit: '세트' },
      { title: '간편식/간식', description: '🔥꿀팁: 컵라면+에너지바+비상식', baseQuantity: 3, unit: '개' },
      { title: '상비약', description: '🔥꿀팁: 두통약+소화제+감기약', baseQuantity: 1, unit: '세트' },
      { title: '신분증+카드', description: '주민증+법인카드+개인카드', baseQuantity: 1, unit: '세트' },
      { title: '출장 영수증 봉투', description: '🔥꿀팁: 정산용 영수증 보관', baseQuantity: 1, unit: '개' },
      { title: '우산/접이식 우산', description: '🔥꿀팁: 날씨 변화 대비', baseQuantity: 1, unit: '개' },
      { title: '여분 옷가방', description: '🔥꿀팁: 선물/기념품용 에코백', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'hospital_admission',
    name: '병원 입원 준비',
    description: '🏥 입원 시 필요한 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '입원 서류', description: '🔥꿀팁: 입원계획서+신분증+보험증+진료의뢰서', baseQuantity: 1, unit: '세트' },
      { title: '보험 관련 서류', description: '🔥꿀팁: 실비보험+생명보험 증서', baseQuantity: 1, unit: '세트' },
      { title: '세면도구', description: '🔥꿀팁: 개인용 칫솔+치약+컵+비누', baseQuantity: 1, unit: '세트' },
      { title: '수건', description: '🔥꿀팁: 개인용 수건 3개(대형+중형+소형)', baseQuantity: 3, unit: '개' },
      { title: '잠옷/환자복', description: '🔥꿀팁: 앞여밈 잠옷+카디건', baseQuantity: 4, unit: '벌' },
      { title: '슬리퍼', description: '🔥꿀팁: 미끄럼방지+쿠션 슬리퍼', baseQuantity: 1, unit: '켤레' },
      { title: '속옷/양말', description: '🔥꿀팁: 일회용 속옷+면 양말', baseQuantity: 7, unit: '벌' },
      { title: '휴지/물티슈', description: '🔥꿀팁: 화장지+물티슈+구강티슈', baseQuantity: 5, unit: '팩' },
      { title: '개인 의료용품', description: '🔥꿀팁: 안경+보청기+틀니+복용약', baseQuantity: 1, unit: '세트' },
      { title: '휴대폰 충전기', description: '🔥꿀팁: 긴 케이블(3m) 충전기', baseQuantity: 1, unit: '개' },
      { title: '휴대폰 거치대', description: '🔥꿀팁: 침상용 각도조절 거치대', baseQuantity: 1, unit: '개' },
      { title: '독서대', description: '🔥꿀팁: 누워서 책/태블릿용', baseQuantity: 1, unit: '개' },
      { title: '보조배터리', description: '🔥꿀팁: 10000mAh 이상', baseQuantity: 1, unit: '개' },
      { title: '이어폰/헤드폰', description: '🔥꿀팁: 병실 소음차단+엔터테인먼트', baseQuantity: 1, unit: '개' },
      { title: '개인 컵/텀블러', description: '🔥꿀팁: 보온병+빨대컵', baseQuantity: 1, unit: '세트' },
      { title: '간식/음식', description: '🔥꿀팁: 죽+미음+소화잘되는 과자', baseQuantity: 5, unit: '개' },
      { title: '비상 연락처', description: '🔥꿀팁: 가족+보험사+직장 연락처', baseQuantity: 1, unit: '개' },
      { title: '현금/카드', description: '🔥꿀팁: 병원 내 소액결제+응급비용', baseQuantity: 100000, unit: '원' },
      { title: '실내화', description: '🔥꿀팁: 재활용 편한 운동화', baseQuantity: 1, unit: '켤레' },
      { title: '개인 베개', description: '🔥꿀팁: 목 편한 개인 베개', baseQuantity: 1, unit: '개' },
      { title: '얇은 담요', description: '🔥꿀팁: 에어컨 추위 대비', baseQuantity: 1, unit: '개' },
      { title: '로션/크림', description: '🔥꿀팁: 병원 건조함 대비 보습제', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'newborn_prep',
    name: '신생아 준비물',
    description: '👶 신생아를 위한 필수 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '기저귀', description: '신생아용 기저귀 (소형)', baseQuantity: 100, unit: '개' },
      { title: '젖병', description: '유리 또는 플라스틱 젖병', baseQuantity: 3, unit: '개' },
      { title: '분유', description: '신생아용 분유', baseQuantity: 2, unit: '통' },
      { title: '아기옷', description: '신생아용 내의, 우주복', baseQuantity: 10, unit: '벌' },
      { title: '속싸개', description: '면 소재 속싸개', baseQuantity: 5, unit: '개' },
      { title: '겉싸개', description: '보온용 겉싸개', baseQuantity: 2, unit: '개' },
      { title: '목욕용품', description: '아기용 비누, 샴푸, 욕조', baseQuantity: 1, unit: '세트' },
      { title: '카시트', description: '신생아용 카시트 (법적 의무)', baseQuantity: 1, unit: '개' },
      { title: '유모차', description: '신생아용 유모차', baseQuantity: 1, unit: '개' },
      { title: '아기 침구', description: '매트리스, 이불, 베개', baseQuantity: 1, unit: '세트' },
      { title: '체온계', description: '귀 또는 이마 체온계', baseQuantity: 1, unit: '개' },
      { title: '수유쿠션', description: '수유 자세 보조용 쿠션', baseQuantity: 1, unit: '개' },
      { title: '아기 손톱가위', description: '신생아 전용 안전 손톱가위', baseQuantity: 1, unit: '개' },
      { title: '공갈 젖꼭지', description: '아기 달래기용 노리개 젖꼭지', baseQuantity: 2, unit: '개' },
      { title: '아기 세탁세제', description: '아기 전용 순한 세탁세제', baseQuantity: 1, unit: '개' },
      { title: '기저귀 크림/연고', description: '기저귀 발진 예방 및 치료용', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'dormitory_prep',
    name: '대학교 기숙사',
    description: '🏫 기숙사 입사 준비물',
    category: '공부',
    peopleMultiplier: false,
    items: [
      { title: '침구류', description: '이불, 베개, 매트리스 커버', baseQuantity: 1, unit: '세트' },
      { title: '세탁용품', description: '세제, 섬유유연제, 빨래바구니', baseQuantity: 1, unit: '세트' },
      { title: '세면도구', description: '칫솔, 치약, 샴푸, 바디워시', baseQuantity: 1, unit: '세트' },
      { title: '수건', description: '목욕용 수건, 세수 수건', baseQuantity: 3, unit: '개' },
      { title: '슬리퍼', description: '실내용 슬리퍼', baseQuantity: 1, unit: '켤레' },
      { title: '옷걸이', description: '옷장용 옷걸이', baseQuantity: 20, unit: '개' },
      { title: '공부용품', description: '노트북, 필기구, 교재', baseQuantity: 1, unit: '세트' },
      { title: '간식', description: '라면, 과자, 음료', baseQuantity: 10, unit: '개' },
      { title: '청소용품', description: '청소기, 걸레, 세제', baseQuantity: 1, unit: '세트' },
      { title: '전기용품', description: '멀티탭, 스탠드, 선풍기', baseQuantity: 1, unit: '세트' },
      { title: '자물쇠/잠금장치', description: '개인 사물함 및 방 보안용', baseQuantity: 1, unit: '개' },
      { title: '미니 냉장고', description: '공용 냉장고 외 개인 식품 보관용', baseQuantity: 1, unit: '개' },
      { title: '에어컨/히터 리모컨 확인', description: '입사 전 냉난방 장치 작동 확인', baseQuantity: 1, unit: '회' },
      { title: '비상약품', description: '두통약, 소화제, 반창고 등 상비약', baseQuantity: 1, unit: '세트' },
      { title: '우산', description: '갑작스런 비 대비 접이식 우산', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'honeymoon_trip',
    name: '신혼여행',
    description: '✈️💕 신혼여행 준비물',
    category: '여행',
    peopleMultiplier: true,
    items: [
      { title: '여권', description: '유효기간 6개월 이상', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '항공권', description: '왕복 항공권', baseQuantity: 1, unit: '매', multiplier: 1 },
      { title: '커플룩', description: '신혼여행용 커플 의상', baseQuantity: 3, unit: '벌' },
      { title: '카메라', description: '추억 촬영용 카메라', baseQuantity: 1, unit: '개' },
      { title: '선크림', description: 'SPF50+ 자외선 차단제', baseQuantity: 2, unit: '개' },
      { title: '수영복', description: '해변/수영장용', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '여행가방', description: '캐리어 또는 여행가방', baseQuantity: 2, unit: '개' },
      { title: '현금', description: '현지 화폐 또는 달러', baseQuantity: 1000, unit: 'USD' },
      { title: '신용카드', description: '해외 결제 가능한 카드', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '상비약', description: '소화제, 감기약, 해열제', baseQuantity: 1, unit: '세트' },
      { title: '충전기', description: '카메라, 핸드폰 충전기', baseQuantity: 1, unit: '세트', multiplier: 1 },
    ]
  },
  {
    id: 'festival_concert',
    name: '페스티벌/콘서트',
    description: '🎵 페스티벌 및 콘서트 준비물',
    category: '여가',
    peopleMultiplier: false,
    items: [
      { title: '티켓', description: '예약 티켓 (모바일/실물)', baseQuantity: 1, unit: '매' },
      { title: '보조배터리', description: '대용량 보조배터리', baseQuantity: 1, unit: '개' },
      { title: '귀마개', description: '소음 차단용 귀마개', baseQuantity: 1, unit: '개' },
      { title: '편한 신발', description: '오래 서있기 편한 운동화', baseQuantity: 1, unit: '켤레' },
      { title: '물병', description: '수분 보충용 물병', baseQuantity: 1, unit: '개' },
      { title: '우비', description: '야외 행사 대비 우비', baseQuantity: 1, unit: '개' },
      { title: '작은 가방', description: '소지품용 작은 가방', baseQuantity: 1, unit: '개' },
      { title: '현금', description: '음식, 굿즈 구매용', baseQuantity: 50000, unit: '원' },
      { title: '휴대폰', description: '사진, 연락용', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '에너지바, 사탕 등', baseQuantity: 3, unit: '개' },
      { title: '손목밴드', description: '입장용 손목밴드', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'ski_snowboard',
    name: '스키/보드',
    description: '⛷️ 겨울 스포츠 준비물',
    category: '운동',
    peopleMultiplier: false,
    items: [
      { title: '스키복', description: '방수 스키복 상하의', baseQuantity: 1, unit: '벌' },
      { title: '스키/보드', description: '렌탈 또는 개인 장비', baseQuantity: 1, unit: '세트' },
      { title: '고글', description: '자외선 차단 고글', baseQuantity: 1, unit: '개' },
      { title: '장갑', description: '방수 스키 장갑', baseQuantity: 1, unit: '켤레' },
      { title: '내의', description: '보온용 기능성 내의', baseQuantity: 2, unit: '벌' },
      { title: '모자', description: '방한용 비니 또는 헬멧', baseQuantity: 1, unit: '개' },
      { title: '리프트권', description: '스키장 리프트 이용권', baseQuantity: 1, unit: '매' },
      { title: '보온병', description: '따뜻한 음료용', baseQuantity: 1, unit: '개' },
      { title: '선크림', description: '설원 자외선 차단제', baseQuantity: 1, unit: '개' },
      { title: '여분 옷', description: '갈아입을 옷', baseQuantity: 1, unit: '벌' },
      { title: '핫팩', description: '손발 보온용', baseQuantity: 10, unit: '개' },
    ]
  },
  {
    id: 'exam_prep',
    name: '시험 준비',
    description: '📚 각종 시험 준비물',
    category: '공부',
    peopleMultiplier: false,
    items: [
      { title: '수험표', description: '시험 응시표 (복사본 포함)', baseQuantity: 2, unit: '매' },
      { title: '신분증', description: '주민등록증 또는 학생증', baseQuantity: 1, unit: '개' },
      { title: '필기구', description: '컴퓨터용 사인펜, 연필', baseQuantity: 5, unit: '개' },
      { title: '지우개', description: '깨끗한 지우개', baseQuantity: 2, unit: '개' },
      { title: '시계', description: '아날로그 시계 (디지털 불가)', baseQuantity: 1, unit: '개' },
      { title: '물', description: '생수 (라벨 제거)', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '초콜릿, 사탕 등 당분 보충', baseQuantity: 2, unit: '개' },
      { title: '마스크', description: '개인 방역용', baseQuantity: 2, unit: '개' },
      { title: '휴대용 선풍기', description: '여름철 더위 대비', baseQuantity: 1, unit: '개' },
      { title: '수정테이프', description: '답안 수정용', baseQuantity: 1, unit: '개' },
    ]
  },
  
  // === 자주 사용되는 일상 템플릿 ===
  {
    id: 'date_prep',
    name: '데이트 준비',
    description: '💕 완벽한 데이트를 위한 준비물',
    category: '여가',
    peopleMultiplier: false,
    items: [
      { title: '지갑', description: '현금, 카드 충분히', baseQuantity: 1, unit: '개' },
      { title: '핸드폰 충전', description: '배터리 100% + 보조배터리', baseQuantity: 1, unit: '개' },
      { title: '데이트 의상', description: '날씨와 장소에 맞는 옷', baseQuantity: 1, unit: '벌' },
      { title: '향수/데오드란트', description: '은은한 향수', baseQuantity: 1, unit: '개' },
      { title: '미니 가방', description: '필수품만 넣을 작은 가방', baseQuantity: 1, unit: '개' },
      { title: '립밤/립틱', description: '입술 관리용', baseQuantity: 1, unit: '개' },
      { title: '티슈/핸드크림', description: '개인위생용품', baseQuantity: 1, unit: '세트' },
      { title: '교통카드', description: '대중교통 이용시', baseQuantity: 1, unit: '개' },
      { title: '마스크', description: '개인 방역용', baseQuantity: 2, unit: '개' },
      { title: '우산', description: '날씨 대비용', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'fishing',
    name: '낚시',
    description: '🎣 바다/강 낚시 준비물',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '낚싯대', description: '바다/민물 낚싯대', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '릴', description: '스피닝 릴', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '낚시줄', description: '목줄, 원줄', baseQuantity: 1, unit: '세트' },
      { title: '바늘/봉돌', description: '다양한 크기 바늘', baseQuantity: 1, unit: '세트' },
      { title: '미끼', description: '지렁이, 새우 등', baseQuantity: 3, unit: '팩' },
      { title: '낚시의자', description: '접이식 의자', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '쿨러', description: '물고기 보관용', baseQuantity: 1, unit: '개' },
      { title: '아이스팩', description: '쿨러용 얼음', baseQuantity: 3, unit: '개' },
      { title: '모자', description: '햇빛 차단용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '선크림', description: 'SPF50+ 필수', baseQuantity: 1, unit: '개' },
      { title: '간식/도시락', description: '하루종일 낚시용', baseQuantity: 3, unit: '개' },
    ]
  },
  {
    id: 'picnic',
    name: '피크닉',
    description: '🧺 공원/야외 피크닉 준비물',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '돗자리', description: '방수 피크닉 매트', baseQuantity: 1, unit: '개' },
      { title: '김밥/샌드위치', description: '피크닉 도시락', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '음료', description: '시원한 음료수', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '과일', description: '씻어온 과일', baseQuantity: 3, unit: '종류' },
      { title: '일회용 접시', description: '종이 접시, 컵', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '젓가락/포크', description: '일회용 수저', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '휴지/물티슈', description: '위생용품', baseQuantity: 3, unit: '팩' },
      { title: '쓰레기봉투', description: '환경보호 필수', baseQuantity: 3, unit: '개' },
      { title: '그늘막/파라솔', description: '햇빛 차단용', baseQuantity: 1, unit: '개' },
      { title: '방충제', description: '벌레 퇴치용', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'home_alone',
    name: '혼자 집 보기',
    description: '🏠 부모님 외출시 집지키기',
    category: '일상',
    peopleMultiplier: false,
    items: [
      { title: '현관문 잠금 확인', description: '도어락 잠금 확인', baseQuantity: 1, unit: '회' },
      { title: '비상연락처', description: '부모님, 경찰서, 소방서', baseQuantity: 1, unit: '리스트' },
      { title: '핸드폰 충전', description: '연락용 핸드폰 충전', baseQuantity: 1, unit: '개' },
      { title: '간단한 식사', description: '라면, 즉석식품', baseQuantity: 2, unit: '개' },
      { title: '음료/물', description: '충분한 수분', baseQuantity: 1, unit: 'L' },
      { title: '간식', description: '과자, 과일', baseQuantity: 3, unit: '개' },
      { title: '휴지/생필품', description: '화장지, 세면용품', baseQuantity: 1, unit: '세트' },
      { title: '오락거리', description: '책, 게임, 영화', baseQuantity: 3, unit: '개' },
      { title: '의약품', description: '상비약, 반창고', baseQuantity: 1, unit: '세트' },
      { title: '손전등', description: '정전 대비', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'car_wash',
    name: '세차',
    description: '🚗 완벽한 셀프 세차 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '세차 샴푸', description: '차량 전용 세제', baseQuantity: 1, unit: '개' },
      { title: '세차 스펀지', description: '부드러운 세차 스펀지', baseQuantity: 2, unit: '개' },
      { title: '마이크로파이버 타월', description: '물기 제거용', baseQuantity: 3, unit: '개' },
      { title: '세차 버킷', description: '세제 희석용 양동이', baseQuantity: 2, unit: '개' },
      { title: '타이어 세정제', description: '타이어/휠 전용', baseQuantity: 1, unit: '개' },
      { title: '유리 세정제', description: '윈도우 클리너', baseQuantity: 1, unit: '개' },
      { title: '왁스/코팅제', description: '광택 및 보호', baseQuantity: 1, unit: '개' },
      { title: '호스/고압세척기', description: '물 분사용', baseQuantity: 1, unit: '개' },
      { title: '고무장갑', description: '손 보호용', baseQuantity: 1, unit: '켤레' },
      { title: '작업복', description: '더러워져도 되는 옷', baseQuantity: 1, unit: '벌' },
    ]
  },
  {
    id: 'pet_walk',
    name: '반려동물 산책',
    description: '🐕 강아지/고양이 산책 준비물',
    category: '일상',
    peopleMultiplier: false,
    items: [
      { title: '목줄/하네스', description: '안전한 목줄', baseQuantity: 1, unit: '개' },
      { title: '리드줄', description: '적절한 길이 리드줄', baseQuantity: 1, unit: '개' },
      { title: '배변봉투', description: '뒷처리용 봉투', baseQuantity: 10, unit: '개' },
      { title: '물과 물그릇', description: '반려동물 수분 보충', baseQuantity: 1, unit: '세트' },
      { title: '간식', description: '훈련용 간식', baseQuantity: 5, unit: '개' },
      { title: '장난감', description: '산책 중 놀이용', baseQuantity: 1, unit: '개' },
      { title: '손 소독제', description: '개인 위생용', baseQuantity: 1, unit: '개' },
      { title: '휴지/물티슈', description: '청소용', baseQuantity: 1, unit: '팩' },
      { title: '응급처치용품', description: '상처 대비', baseQuantity: 1, unit: '세트' },
      { title: '반려동물 등록증', description: '신분증', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'beach_trip',
    name: '해수욕장',
    description: '🏖️ 여름 바다 여행 준비물',
    category: '여행',
    peopleMultiplier: true,
    items: [
      { title: '수영복', description: '바다 수영용', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '비치타월', description: '큰 해변 타월', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '선크림', description: 'SPF50+ 방수', baseQuantity: 2, unit: '개' },
      { title: '비치 파라솔', description: '그늘막', baseQuantity: 1, unit: '개' },
      { title: '비치볼/튜브', description: '바다 놀이용품', baseQuantity: 3, unit: '개' },
      { title: '수경/스노클', description: '물놀이용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '비치샌들', description: '물에 젖어도 되는 신발', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '방수가방', description: '소지품 보관용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '시원한 음료', description: '갈증 해소용', baseQuantity: 3, unit: '개', multiplier: 1 },
      { title: '간식', description: '바다에서 먹을 간식', baseQuantity: 5, unit: '개' },
      { title: '응급처치용품', description: '해파리 쏘임 대비', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'mountain_hiking',
    name: '산 등반 (고난도)',
    description: '⛰️ 높은 산 등반 준비물',
    category: '아웃도어',
    peopleMultiplier: true,
    items: [
      { title: '등산화', description: '발목 보호 전문 등산화', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '등산복', description: '기능성 등산복 상하', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '등산가방', description: '40L 이상 백팩', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '충분한 물', description: '2L 이상 생수', baseQuantity: 2, unit: 'L', multiplier: 1 },
      { title: '행동식', description: '에너지바, 견과류', baseQuantity: 5, unit: '개', multiplier: 1 },
      { title: '등산스틱', description: '트레킹 폴 2개', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '헤드랜턴', description: '야간/새벽 등반용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '레인코트', description: '갑작스런 비 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '응급처치용품', description: '부상 대비 구급약', baseQuantity: 1, unit: '세트' },
      { title: '등산지도/GPS', description: '길찾기용', baseQuantity: 1, unit: '개' },
      { title: '호루라기', description: '조난 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
    ]
  },
  {
    id: 'karaoke',
    name: '노래방',
    description: '🎤 친구들과 노래방 준비물',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '현금', description: '노래방 비용 + 연장비', baseQuantity: 50000, unit: '원' },
      { title: '음료/안주', description: '콜라, 맥주, 과자', baseQuantity: 5, unit: '개' },
      { title: '핸드폰', description: '노래 검색, 촬영용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '보조배터리', description: '핸드폰 충전용', baseQuantity: 1, unit: '개' },
      { title: '목캔디/목스프레이', description: '목 관리용', baseQuantity: 1, unit: '개' },
      { title: '물', description: '수분 보충용', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '마스크', description: '개인 방역용', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '손 소독제', description: '위생용', baseQuantity: 1, unit: '개' },
      { title: '교통카드/택시비', description: '귀가용', baseQuantity: 1, unit: '세트' },
      { title: '즐거운 마음', description: '흥 가득한 마음가짐', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'apartment_viewing',
    name: '부동산 집보기',
    description: '🏠 원룸/아파트 매물 볼 때 준비물 + 현장 체크리스트',
    category: '생활',
    peopleMultiplier: false,
    items: [
      // 준비물
      { title: '신분증', description: '본인 확인용', baseQuantity: 1, unit: '개' },
      { title: '메모장/펜', description: '매물 정보 기록용', baseQuantity: 1, unit: '세트' },
      { title: '핸드폰', description: '사진/영상 촬영, 연락용', baseQuantity: 1, unit: '개' },
      { title: '줄자', description: '가구 배치 측정용', baseQuantity: 1, unit: '개' },
      { title: '계약 관련 서류', description: '소득증명서, 통장사본 등', baseQuantity: 1, unit: '세트' },
      // 수압/배수
      { title: '수압 확인', description: '싱크대, 화장실 수도 틀어보기', baseQuantity: 1, unit: '건' },
      { title: '온수 확인', description: '온수 나오는지, 나오는 속도 체크', baseQuantity: 1, unit: '건' },
      { title: '배수 확인', description: '싱크대, 세면대, 화장실 배수 잘 되는지', baseQuantity: 1, unit: '건' },
      { title: '변기 물 내리기', description: '수압, 역류 여부 확인', baseQuantity: 1, unit: '건' },
      // 채광/환기/소음
      { title: '채광 확인', description: '낮에 방문해서 햇빛 들어오는지 확인', baseQuantity: 1, unit: '건' },
      { title: '창문 방향', description: '남향/동향 등 확인, 앞 건물 가림 여부', baseQuantity: 1, unit: '건' },
      { title: '단열/외풍', description: '창문 닫고 외풍 확인, 이중창 여부, 실리콘 상태', baseQuantity: 1, unit: '건' },
      { title: '소음 확인', description: '도로/골목 소음, 주변 유흥가/공사장 여부', baseQuantity: 1, unit: '건' },
      { title: '방음/층간소음', description: '벽 두드려서 두께 확인, 윗층/옆집 소리', baseQuantity: 1, unit: '건' },
      { title: '환기 상태', description: '창문 개폐 잘 되는지, 환풍기 작동 확인', baseQuantity: 1, unit: '건' },
      // 상태 점검
      { title: '곰팡이/습기', description: '벽, 천장, 화장실, 창문 틀 곰팡이 확인', baseQuantity: 1, unit: '건' },
      { title: '벽지/바닥 상태', description: '들뜸, 찢어짐, 얼룩 확인', baseQuantity: 1, unit: '건' },
      { title: '보일러/난방', description: '작동 여부, 연식, 개별/중앙난방 확인', baseQuantity: 1, unit: '건' },
      { title: '콘센트 확인', description: '개수, 위치, 작동 여부 확인', baseQuantity: 1, unit: '건' },
      { title: '벌레/해충 흔적', description: '바퀴벌레 트랩, 구석 흔적, 1층 음식점 여부', baseQuantity: 1, unit: '건' },
      { title: '옵션 가전 상태', description: '에어컨, 냉장고, 세탁기, 인덕션 작동/연식 확인', baseQuantity: 1, unit: '건' },
      { title: '수납공간', description: '옷장, 신발장, 서랍 등 수납 충분한지 확인', baseQuantity: 1, unit: '건' },
      { title: '화장실 환풍', description: '화장실 창문 또는 환풍기 유무 (없으면 곰팡이 심함)', baseQuantity: 1, unit: '건' },
      // 보안/편의
      { title: '현관문 잠금장치', description: '도어락 상태, 이중잠금 여부', baseQuantity: 1, unit: '건' },
      { title: 'CCTV/보안', description: '건물 입구, 복도, 주차장 CCTV 확인', baseQuantity: 1, unit: '건' },
      { title: '야간 치안', description: '귀갓길 가로등, CCTV, 인적 확인 (저녁에도 방문)', baseQuantity: 1, unit: '건' },
      { title: '핸드폰 수신', description: '집 안에서 통신 상태 확인', baseQuantity: 1, unit: '건' },
      { title: '엘리베이터', description: '고층이면 엘리베이터 유무, 이사 시 필수', baseQuantity: 1, unit: '건' },
      // 주변 환경
      { title: '교통 접근성', description: '역/버스 정류장 도보 거리 확인', baseQuantity: 1, unit: '건' },
      { title: '편의시설', description: '편의점, 마트, 세탁소 등 주변 확인', baseQuantity: 1, unit: '건' },
      { title: '쓰레기 배출', description: '분리수거장 위치, 음식물 처리방식 확인', baseQuantity: 1, unit: '건' },
      { title: '주차 공간', description: '주차 가능 여부, 추가비용 확인', baseQuantity: 1, unit: '건' },
      { title: '1층 상가 확인', description: '고깃집/술집 있으면 냄새, 소음, 벌레 유입 주의', baseQuantity: 1, unit: '건' },
      // 비용/계약
      { title: '관리비 확인', description: '포함 항목 세부 확인 (전기/수도/가스/인터넷)', baseQuantity: 1, unit: '건' },
      { title: '계량기 분리 여부', description: '전기/수도 세대별 분리 안 되면 타 세대 부담 가능', baseQuantity: 1, unit: '건' },
      { title: '등기부등본 확인', description: '근저당, 압류 등 권리관계 확인 (전세사기 예방)', baseQuantity: 1, unit: '건' },
      { title: '전입신고 가능 여부', description: '전입신고 불가하면 대항력 확보 못함', baseQuantity: 1, unit: '건' },
    ]
  },

  // === 계절별 특화 템플릿 ===
  {
    id: 'summer_festival',
    name: '여름 축제',
    description: '🎆 여름 축제/불꽃축제 준비물',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '돗자리', description: '앉을 자리 확보용', baseQuantity: 1, unit: '개' },
      { title: '부채/휴대용 선풍기', description: '더위 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '시원한 음료', description: '갈증 해소용', baseQuantity: 3, unit: '개', multiplier: 1 },
      { title: '얼음/아이스팩', description: '시원함 유지', baseQuantity: 2, unit: '개' },
      { title: '모자', description: '햇빛 차단용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '선크림', description: '자외선 차단', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '축제 간식', baseQuantity: 5, unit: '개' },
      { title: '방충제', description: '모기 퇴치용', baseQuantity: 1, unit: '개' },
      { title: '카메라/핸드폰', description: '추억 기록용', baseQuantity: 1, unit: '개' },
      { title: '쓰레기봉투', description: '뒷정리용', baseQuantity: 3, unit: '개' },
    ]
  },
  {
    id: 'winter_activity',
    name: '겨울 야외활동',
    description: '❄️ 겨울 야외활동 준비물',
    category: '아웃도어',
    peopleMultiplier: true,
    items: [
      { title: '패딩/두꺼운 옷', description: '방한용 외투', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '방한 모자', description: '귀까지 덮는 모자', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '장갑', description: '방수 방한 장갑', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '목도리', description: '목 보온용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '방한 신발', description: '미끄럼 방지 신발', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '핫팩', description: '몸 곳곳 보온용', baseQuantity: 10, unit: '개' },
      { title: '보온 음료', description: '따뜻한 차/커피', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '립밤', description: '입술 건조 방지', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '핸드크림', description: '손 건조 방지', baseQuantity: 1, unit: '개' },
      { title: '여분 양말', description: '발 보온용', baseQuantity: 1, unit: '켤레', multiplier: 1 },
    ]
  },

  // === 데이트/연인 관련 템플릿 ===
  {
    id: 'cherry_blossom_date',
    name: '벚꽃구경 데이트',
    description: '🌸 봄 벚꽃놀이 데이트',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '돗자리', description: '벚꽃 아래 앉을 매트', baseQuantity: 1, unit: '개' },
      { title: '김밥/도시락', description: '야외에서 먹을 음식', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '음료', description: '시원한 음료수', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '카메라', description: '벚꽃 인생샷용', baseQuantity: 1, unit: '개' },
      { title: '보조배터리', description: '사진 많이 찍을 때', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '벚꽃빵, 딸기 등', baseQuantity: 3, unit: '개' },
      { title: '휴지/물티슈', description: '음식 먹고 뒷정리', baseQuantity: 1, unit: '팩' },
      { title: '쓰레기봉투', description: '환경보호 필수', baseQuantity: 2, unit: '개' },
      { title: '가디건/얇은 외투', description: '봄날씨 변화 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '선크림', description: '야외활동 자외선 차단', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'movie_date',
    name: '영화관 데이트',
    description: '🎬 영화 보고 식사하기',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '영화표', description: '미리 예매한 티켓', baseQuantity: 1, unit: '매', multiplier: 1 },
      { title: '현금/카드', description: '팝콘, 음료, 식사비', baseQuantity: 50000, unit: '원' },
      { title: '핸드폰', description: '예매 확인+연락용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '마스크', description: '밀폐공간 방역', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '손수건', description: '감동적인 영화 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '민트/껌', description: '가까이 앉는 상황', baseQuantity: 1, unit: '개' },
      { title: '가벼운 가방', description: '소지품 보관용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '교통카드', description: '영화관 이동용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '따뜻한 옷', description: '영화관 에어컨 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '좋은 기분', description: '즐거운 데이트 분위기', baseQuantity: 1, unit: '개', multiplier: 1 },
    ]
  },
  {
    id: 'han_river_date',
    name: '한강 데이트',
    description: '🌊 한강공원에서 치킨+맥주',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '치킨', description: '한강 치킨은 필수', baseQuantity: 1, unit: '마리' },
      { title: '맥주/소주', description: '치킨과 완벽한 조합', baseQuantity: 4, unit: '캔', multiplier: 1 },
      { title: '돗자리', description: '한강 잔디밭용', baseQuantity: 1, unit: '개' },
      { title: '블루투스 스피커', description: '분위기 음악', baseQuantity: 1, unit: '개' },
      { title: '휴지/물티슈', description: '치킨 기름 닦기', baseQuantity: 2, unit: '팩' },
      { title: '쓰레기봉투', description: '치킨뼈 담을 봉투', baseQuantity: 3, unit: '개' },
      { title: '카메라', description: '한강 야경 촬영', baseQuantity: 1, unit: '개' },
      { title: '보조배터리', description: '음악+사진 촬영', baseQuantity: 1, unit: '개' },
      { title: '간단한 안주', description: '오징어, 견과류 등', baseQuantity: 2, unit: '개' },
      { title: '따뜻한 옷', description: '한강 바람 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
    ]
  },
  {
    id: 'couple_cafe',
    name: '카페 데이트',
    description: '☕ 감성 카페에서 대화하기',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '지갑', description: '카페 음료+디저트 비용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '핸드폰', description: '카페 인증샷+음악', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '보조배터리', description: '긴 시간 카페 이용', baseQuantity: 1, unit: '개' },
      { title: '이어폰', description: '함께 음악 들을 때', baseQuantity: 1, unit: '개' },
      { title: '핸드크림', description: '건조한 카페 대비', baseQuantity: 1, unit: '개' },
      { title: '립밤', description: '대화 많이 할 때', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '마스크', description: '개인 방역용', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '가벼운 외투', description: '카페 에어컨 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '카드/현금', description: '결제수단', baseQuantity: 30000, unit: '원' },
      { title: '대화 주제', description: '즐거운 대화거리', baseQuantity: 5, unit: '개' },
    ]
  },
  {
    id: 'amusement_park_date',
    name: '놀이공원 데이트',
    description: '🎢 롯데월드/에버랜드 데이트',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '입장권', description: '놀이공원 입장 티켓', baseQuantity: 1, unit: '매', multiplier: 1 },
      { title: '편한 신발', description: '하루 종일 걸을 운동화', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '가벼운 가방', description: '소지품용 크로스백', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '물', description: '갈증 해소용', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '간식', description: '에너지바, 사탕', baseQuantity: 5, unit: '개' },
      { title: '보조배터리', description: '사진+대기시간 대비', baseQuantity: 1, unit: '개' },
      { title: '현금', description: '음식+기념품 구매', baseQuantity: 100000, unit: '원' },
      { title: '선크림', description: '야외 놀이기구 대비', baseQuantity: 1, unit: '개' },
      { title: '모자', description: '햇빛 차단용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '멀미약', description: '스릴 넘치는 놀이기구', baseQuantity: 2, unit: '개', multiplier: 1 },
    ]
  },
  {
    id: 'night_market_date',
    name: '야시장 데이트',
    description: '🌙 동대문/홍대 야시장 구경',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '현금', description: '야시장 음식+쇼핑', baseQuantity: 50000, unit: '원' },
      { title: '에코백', description: '쇼핑한 물건 담기', baseQuantity: 2, unit: '개' },
      { title: '편한 신발', description: '오래 걸어도 편한 신발', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '물티슈', description: '야시장 음식 먹고', baseQuantity: 1, unit: '팩' },
      { title: '핸드폰', description: '야시장 인증샷', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '보조배터리', description: '밤늦게까지 사용', baseQuantity: 1, unit: '개' },
      { title: '마스크', description: '사람 많은 곳', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '손 소독제', description: '음식 먹기 전', baseQuantity: 1, unit: '개' },
      { title: '카드', description: '일부 업체 카드 결제', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '호기심', description: '새로운 음식 도전정신', baseQuantity: 1, unit: '개', multiplier: 1 },
    ]
  },
  {
    id: 'beach_date',
    name: '바다 데이트',
    description: '🏖️ 해변에서 로맨틱한 시간',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '선크림', description: 'SPF50+ 방수 선크림', baseQuantity: 2, unit: '개' },
      { title: '비치타월', description: '모래사장용 큰 수건', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '선글라스', description: '바다 햇빛 차단', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '모자', description: '넓은 챙 모자', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '시원한 음료', description: '갈증 해소용', baseQuantity: 3, unit: '개', multiplier: 1 },
      { title: '간식', description: '바다에서 먹을 간식', baseQuantity: 5, unit: '개' },
      { title: '방수가방', description: '소지품 보관', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '샌들', description: '모래사장용 신발', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '카메라', description: '바다 인증샷', baseQuantity: 1, unit: '개' },
      { title: '여분 옷', description: '바닷바람 대비', baseQuantity: 1, unit: '벌', multiplier: 1 },
    ]
  },

  // === 한국인 생활 밀착형 템플릿 ===
  {
    id: 'subway_commute',
    name: '지하철 출근',
    description: '🚇 서울 지하철 출근 준비물',
    category: '일상',
    peopleMultiplier: false,
    items: [
      { title: '교통카드', description: '티머니/하나로/원패스', baseQuantity: 1, unit: '개' },
      { title: '핸드폰', description: '길찾기+음악+웹툰', baseQuantity: 1, unit: '개' },
      { title: '보조배터리', description: '출퇴근 긴 시간 대비', baseQuantity: 1, unit: '개' },
      { title: '이어폰', description: '지하철 소음 차단', baseQuantity: 1, unit: '개' },
      { title: '마스크', description: '미세먼지+방역', baseQuantity: 2, unit: '개' },
      { title: '손수건/휴지', description: '땀+콧물 대비', baseQuantity: 1, unit: '팩' },
      { title: '회사카드', description: '사원증/출입카드', baseQuantity: 1, unit: '개' },
      { title: '우산', description: '갑작스런 비 대비', baseQuantity: 1, unit: '개' },
      { title: '물/음료', description: '러시아워 갈증 대비', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '아침 거른 날 대비', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'korean_bbq',
    name: '삼겹살 파티',
    description: '🥓 집에서 고기 구워먹기',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '삼겹살', description: '1인당 200g 기준', baseQuantity: 200, unit: 'g', multiplier: 1 },
      { title: '상추/깻잎', description: '쌈채소', baseQuantity: 1, unit: '봉지' },
      { title: '된장찌개', description: '고기의 기본 반찬', baseQuantity: 1, unit: '개' },
      { title: '김치', description: '잘 익은 배추김치', baseQuantity: 1, unit: '포기' },
      { title: '소주/맥주', description: '고기엔 술이지', baseQuantity: 2, unit: '병', multiplier: 1 },
      { title: '마늘', description: '구운 마늘', baseQuantity: 1, unit: '통' },
      { title: '부추', description: '양념 부추', baseQuantity: 1, unit: '단' },
      { title: '쌈장', description: '상추쌈용', baseQuantity: 1, unit: '개' },
      { title: '휴대용 가스레인지', description: '고기 굽는 기구', baseQuantity: 1, unit: '개' },
      { title: '일회용 접시', description: '뒷정리 편한 그릇', baseQuantity: 1, unit: '세트', multiplier: 1 },
    ]
  },
  {
    id: 'korean_sauna',
    name: '찜질방/사우나',
    description: '🧖‍♀️ 한국 찜질방 완전정복',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '세면도구', description: '샴푸, 바디워시, 클렌징', baseQuantity: 1, unit: '세트' },
      { title: '수건', description: '개인 수건 (대형)', baseQuantity: 2, unit: '개' },
      { title: '찜질방 의상', description: '편한 실내복', baseQuantity: 1, unit: '벌' },
      { title: '슬리퍼', description: '미끄럼방지 슬리퍼', baseQuantity: 1, unit: '켤레' },
      { title: '현금', description: '찜질방 비용+간식비', baseQuantity: 20000, unit: '원' },
      { title: '핸드폰 방수팩', description: '사우나 습기 대비', baseQuantity: 1, unit: '개' },
      { title: '헤어타이', description: '머리 묶을 끈', baseQuantity: 3, unit: '개' },
      { title: '화장지', description: '개인 화장지', baseQuantity: 1, unit: '개' },
      { title: '로션/크림', description: '사우나 후 보습', baseQuantity: 1, unit: '개' },
      { title: '간식비', description: '맥반석계란+식혜', baseQuantity: 10000, unit: '원' },
    ]
  },
  {
    id: 'korean_hiking',
    name: '동네 뒷산 등산',
    description: '⛰️ 서울 근교 가벼운 등산',
    category: '운동',
    peopleMultiplier: true,
    items: [
      { title: '등산화', description: '발목 보호 운동화', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '등산복', description: '땀 배출 잘되는 옷', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '물', description: '1인당 1L 이상', baseQuantity: 1, unit: 'L', multiplier: 1 },
      { title: '간식', description: '초콜릿, 견과류', baseQuantity: 3, unit: '개', multiplier: 1 },
      { title: '등산스틱', description: '접이식 스틱', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '모자', description: '햇빛 차단용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '수건', description: '땀 닦을 수건', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '쓰레기봉투', description: '환경보호 필수', baseQuantity: 3, unit: '개' },
      { title: '현금', description: '산 위 매점비', baseQuantity: 20000, unit: '원' },
      { title: '핸드폰', description: '길찾기+인증샷', baseQuantity: 1, unit: '개', multiplier: 1 },
    ]
  },
  {
    id: 'korean_wedding',
    name: '한국 결혼식 참석',
    description: '👰 결혼식 하객 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '축의금', description: '관계별 적정 금액', baseQuantity: 100000, unit: '원' },
      { title: '축의금 봉투', description: '흰 봉투+검은 펜', baseQuantity: 1, unit: '개' },
      { title: '정장/한복', description: '격식 맞는 의상', baseQuantity: 1, unit: '벌' },
      { title: '구두/힐', description: '정장에 맞는 신발', baseQuantity: 1, unit: '켤레' },
      { title: '핸드백', description: '작은 격식용 가방', baseQuantity: 1, unit: '개' },
      { title: '휴대폰', description: '초대장+사진촬영', baseQuantity: 1, unit: '개' },
      { title: '교통비', description: '웨딩홀 왕복', baseQuantity: 20000, unit: '원' },
      { title: '포켓 티슈', description: '감동의 눈물 대비', baseQuantity: 1, unit: '개' },
      { title: '립스틱/화장품', description: '화장 고침용', baseQuantity: 1, unit: '세트' },
      { title: '축하 마음', description: '진심 어린 축하', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'korean_pc_cafe',
    name: 'PC방',
    description: '🎮 한국 PC방 완전정복',
    category: '여가',
    peopleMultiplier: false,
    items: [
      { title: '현금', description: 'PC방 이용료+음식값', baseQuantity: 20000, unit: '원' },
      { title: '신분증', description: '회원가입/본인인증', baseQuantity: 1, unit: '개' },
      { title: '핸드폰', description: '친구 연락+인증', baseQuantity: 1, unit: '개' },
      { title: '이어폰/헤드셋', description: '개인 청취용', baseQuantity: 1, unit: '개' },
      { title: '게임 계정', description: '로그인 정보 암기', baseQuantity: 1, unit: '개' },
      { title: '간식비', description: '라면+음료 주문비', baseQuantity: 10000, unit: '원' },
      { title: '손목보호대', description: '장시간 게임 대비', baseQuantity: 1, unit: '개' },
      { title: '안경', description: '눈 보호용', baseQuantity: 1, unit: '개' },
      { title: '마스크', description: '개인 위생용', baseQuantity: 1, unit: '개' },
      { title: '게임할 마음', description: '진정한 게이머의 자세', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'chuseok_prep',
    name: '추석 차례상',
    description: '🌕 추석 명절 차례 준비',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '과일', description: '사과, 배, 대추', baseQuantity: 3, unit: '종류' },
      { title: '나물', description: '도라지, 고사리, 시금치', baseQuantity: 3, unit: '접시' },
      { title: '전', description: '동그랑땡, 파전', baseQuantity: 2, unit: '접시' },
      { title: '탕', description: '갈비탕 또는 육개장', baseQuantity: 1, unit: '그릇' },
      { title: '밥', description: '햇쌀로 지은 밥', baseQuantity: 1, unit: '그릇' },
      { title: '술', description: '청주 또는 소주', baseQuantity: 1, unit: '병' },
      { title: '향', description: '선조님께 올릴 향', baseQuantity: 3, unit: '개' },
      { title: '초', description: '제사상 촛불', baseQuantity: 2, unit: '개' },
      { title: '한복/정장', description: '차례복 준비', baseQuantity: 1, unit: '벌' },
      { title: '선물', description: '어른들께 드릴 선물', baseQuantity: 3, unit: '개' },
    ]
  },
  {
    id: 'korean_study_cafe',
    name: '스터디 카페',
    description: '📚 한국 스터디 카페 이용',
    category: '공부',
    peopleMultiplier: false,
    items: [
      { title: '학생증/신분증', description: '할인+본인인증', baseQuantity: 1, unit: '개' },
      { title: '현금', description: '이용료+음료비', baseQuantity: 15000, unit: '원' },
      { title: '필기구', description: '볼펜, 형광펜, 연필', baseQuantity: 1, unit: '세트' },
      { title: '교재/노트', description: '공부할 책', baseQuantity: 3, unit: '권' },
      { title: '노트북/태블릿', description: '디지털 학습도구', baseQuantity: 1, unit: '개' },
      { title: '충전기', description: '전자기기 충전용', baseQuantity: 1, unit: '개' },
      { title: '이어폰', description: '집중력 향상용', baseQuantity: 1, unit: '개' },
      { title: '개인컵', description: '무료 음료용', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '당분 보충용', baseQuantity: 2, unit: '개' },
      { title: '슬리퍼', description: '편안한 공부환경', baseQuantity: 1, unit: '켤레' },
    ]
  },
  {
    id: 'korean_convenience',
    name: '편의점 야식',
    description: '🍜 편의점 야식 조합',
    category: '일상',
    peopleMultiplier: true,
    items: [
      { title: '컵라면', description: '신라면, 짜파게티', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '삼각김밥', description: '참치, 불고기', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '음료', description: '콜라, 사이다', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '과자', description: '허니버터칩, 새우깡', baseQuantity: 1, unit: '개' },
      { title: '아이스크림', description: '빙그레, 하겐다즈', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '현금/카드', description: '결제수단', baseQuantity: 10000, unit: '원' },
      { title: '에코백', description: '편의점 봉투 대신', baseQuantity: 1, unit: '개' },
      { title: '포크/젓가락', description: '편의점 무료제공', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '물', description: '짠 야식 후 갈증', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '친구들', description: '함께 먹을 사람들', baseQuantity: 1, unit: '명', multiplier: 1 },
    ]
  },
  {
    id: 'korean_apartment',
    name: '원룸 이사',
    description: '🏠 대학생/직장인 원룸 이사',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '이사업체', description: '포장이사/반포장', baseQuantity: 1, unit: '업체' },
      { title: '박스', description: '이삿짐 포장용', baseQuantity: 20, unit: '개' },
      { title: '테이프', description: '박스 밀봉용', baseQuantity: 5, unit: '개' },
      { title: '뽁뽁이', description: '깨지기 쉬운 물건', baseQuantity: 10, unit: 'm' },
      { title: '매직펜', description: '박스 라벨링', baseQuantity: 3, unit: '개' },
      { title: '청소용품', description: '구집 청소용', baseQuantity: 1, unit: '세트' },
      { title: '주소변경', description: '주민등록 이전', baseQuantity: 1, unit: '건' },
      { title: '택배 주소변경', description: '쿠팡, 11번가 등', baseQuantity: 1, unit: '건' },
      { title: '이사 간식', description: '이삿짐센터 간식', baseQuantity: 1, unit: '세트' },
      { title: '현금', description: '이삿짐센터 팁', baseQuantity: 100000, unit: '원' },
    ]
  },

  // === 기존 템플릿 (일상 루틴) ===
  {
    id: 'morning_work',
    name: '출근 준비',
    description: '깜빡하기 쉬운 출근 필수템들',
    category: '일상',
    peopleMultiplier: false,
    items: [
      { title: '지갑', description: '신용카드, 현금, 신분증', baseQuantity: 1, unit: '개' },
      { title: '교통카드', description: '지하철/버스 카드', baseQuantity: 1, unit: '개' },
      { title: '회사 출입카드', description: '사원증/출입카드', baseQuantity: 1, unit: '개' },
      { title: '핸드폰', description: '충전 확인', baseQuantity: 1, unit: '개' },
      { title: '이어폰', description: '무선/유선 이어폰', baseQuantity: 1, unit: '개' },
      { title: '마스크', description: '개인 방역용', baseQuantity: 2, unit: '개' },
      { title: '우산', description: '날씨 확인 후', baseQuantity: 1, unit: '개' },
      { title: '텀블러', description: '카페 할인 + 환경보호', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '오후 허기 대비', baseQuantity: 1, unit: '개' },
      { title: '충전기', description: '휴대용 보조배터리', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'gym_prep',
    name: '헬스장 준비',
    description: '운동 효과 극대화 + 꿀팁 준비물',
    category: '운동',
    peopleMultiplier: false,
    items: [
      { title: '운동복', description: '땀 배출 좋은 드라이핏', baseQuantity: 1, unit: '벌' },
      { title: '여분 속옷', description: '🔥꿀팁: 운동 후 갈아입기', baseQuantity: 1, unit: '벌' },
      { title: '운동화', description: '웨이트용 평평한 밑창', baseQuantity: 1, unit: '켤레' },
      { title: '운동장갑', description: '🔥꿀팁: 손바닥 굳은살 방지', baseQuantity: 1, unit: '개' },
      { title: '수건', description: '개인 수건 (대형)', baseQuantity: 1, unit: '개' },
      { title: '물병', description: '1L 이상 + 전해질', baseQuantity: 1, unit: '개' },
      { title: '이어폰', description: '🔥꿀팁: 무선 추천 (선 걸림 방지)', baseQuantity: 1, unit: '개' },
      { title: '운동 기록장', description: '🔥꿀팁: 중량/횟수 기록', baseQuantity: 1, unit: '개' },
      { title: '프로틴/BCAA', description: '운동 후 30분 골든타임', baseQuantity: 1, unit: '개' },
      { title: '리프팅 스트랩', description: '🔥꿀팁: 데드리프트 그립력 보조', baseQuantity: 1, unit: '개' },
      { title: '샤워용품', description: '샴푸+바디워시+슬리퍼', baseQuantity: 1, unit: '세트' },
      { title: '헬스장 카드', description: '출입용 + 락커키', baseQuantity: 1, unit: '개' },
      { title: '작은 타월', description: '🔥꿀팁: 운동 중 얼굴 땀 닦기', baseQuantity: 1, unit: '개' },
      { title: '손목보호대', description: '🔥꿀팁: 벤치프레스/프레스 필수', baseQuantity: 1, unit: '개' },
      { title: '팔꿈치 보호대', description: '🔥꿀팁: 테니스엘보우 예방', baseQuantity: 1, unit: '개' },
      { title: '고중량용 복압벨트', description: '🔥꿀팁: 데드리프트/스쿼트 안전', baseQuantity: 1, unit: '개' },
      { title: '무릎보호대', description: '🔥꿀팁: 스쿼트/런지 무릎보호', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'camping',
    name: '캠핑',
    description: '완벽한 캠핑을 위한 필수 준비물',
    category: '아웃도어',
    peopleMultiplier: true,
    items: [
      { title: '텐트', description: '🏕️ 방수+통풍 기능 텐트', baseQuantity: 1, unit: '개' },
      { title: '타프', description: '그늘막/비막이 겸용', baseQuantity: 1, unit: '개' },
      { title: '그라운드시트', description: '텐트 바닥 방수포', baseQuantity: 1, unit: '개' },
      { title: '침낭', description: '🛏️ 계절에 맞는 침낭', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '매트/에어매트', description: '바닥 쿠션 매트', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '베개', description: '🔥꿀팁: 접이식 베개 필수', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '캠핑 테이블', description: '접이식 캠핑 테이블', baseQuantity: 1, unit: '개' },
      { title: '캠핑 의자', description: '🪑 접이식 의자', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '버너/가스', description: '요리용 캠핑 버너+가스', baseQuantity: 1, unit: '세트' },
      { title: '코펠/냄비', description: '🔥꿀팁: 다양한 사이즈 냄비 세트', baseQuantity: 1, unit: '세트' },
      { title: '불판', description: '🔥꿀팁: 논스틱 불판 필수', baseQuantity: 1, unit: '개' },
      { title: '집게/가위', description: '🔥꿀팁: 고기용 집게+다용도 가위', baseQuantity: 1, unit: '세트' },
      { title: '키친타월', description: '🔥꿀팁: 물젖은 손 닦기+기름제거', baseQuantity: 3, unit: '롤' },
      { title: '바베큐 그릴', description: '숯불/가스 바베큐 그릴', baseQuantity: 1, unit: '개' },
      { title: '고기/식재료', description: '🥩 바베큐용 고기+채소 (1인당 200g)', baseQuantity: 200, unit: 'g', multiplier: 1 },
      { title: '숯/착화제', description: '바베큐용 숯+착화제', baseQuantity: 1, unit: '세트' },
      { title: '물', description: '💧 식수+세척용', baseQuantity: 2, unit: 'L', multiplier: 1 },
      { title: '아이스박스/쿨러', description: '🔥꿀팁: 크기별 2개 준비(음료용+식재료용)', baseQuantity: 1, unit: '세트' },
      { title: '아이스팩', description: '쿨러박스용 얼음+보냉팩', baseQuantity: 5, unit: '개' },
      { title: '랜턴', description: '🏮 LED 랜턴+헤드랜턴', baseQuantity: 2, unit: '개' },
      { title: '보조배터리', description: '🔋 20000mAh 이상', baseQuantity: 1, unit: '개' },
      { title: '블루투스 스피커', description: '🎵 방수 스피커', baseQuantity: 1, unit: '개' },
      { title: '멀티툴', description: '만능 캠핑 도구', baseQuantity: 1, unit: '개' },
      { title: '로프/펙', description: '텐트/타프 고정용', baseQuantity: 1, unit: '세트' },
      { title: '휴지/물티슈', description: '🔥꿀팁: 화장지+물티슈 여유분', baseQuantity: 2, unit: '팩' },
      { title: '쓰레기봉투', description: '🔥꿀팁: 종량제+분리수거용', baseQuantity: 5, unit: '개' },
    ]
  },
  {
    id: 'car_camping',
    name: '차박 (차박/카캠핑)',
    description: '🚗 차 안에서 자는 차박 완벽 준비물',
    category: '아웃도어',
    peopleMultiplier: true,
    items: [
      { title: '차량용 커튼/블랙아웃', description: '🔥꿀팁: 프라이버시+숙면 필수', baseQuantity: 1, unit: '세트' },
      { title: '차량용 매트리스', description: '🔥꿀팁: 플랫폼 매트리스 or 에어매트', baseQuantity: 1, unit: '개' },
      { title: '이불/침낭', description: '🔥꿀팁: 겨울철 두꺼운 이불 필수', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '베개', description: '🔥꿀팁: 목 편한 베개+여분 베개', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '차량용 선풍기', description: '🔥꿀팁: 12V 차량용 or USB 선풍기', baseQuantity: 1, unit: '개' },
      { title: '차량용 히터', description: '🔥꿀팁: 겨울 차박 생명 안전템', baseQuantity: 1, unit: '개' },
      { title: '차량용 냉장고', description: '음식 보관+차가운 음료', baseQuantity: 1, unit: '개' },
      { title: '아이스박스', description: '🔥꿀팁: 냉장고 없으면 필수템', baseQuantity: 1, unit: '개' },
      { title: '아이스팩', description: '아이스박스용 얼음', baseQuantity: 5, unit: '개' },
      { title: '캠핑 테이블', description: '🔥꿀팁: 접이식 높이조절 테이블', baseQuantity: 1, unit: '개' },
      { title: '캠핑 의자', description: '🔥꿀팁: 등받이 있는 편안한 의자', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '버너/가스', description: '🔥꿀팁: 카세트 버너+여분 가스', baseQuantity: 1, unit: '세트' },
      { title: '냄비', description: '🔥꿀팁: 크기별 냄비 2-3개', baseQuantity: 1, unit: '세트' },
      { title: '불판', description: '🔥꿀팁: 논스틱 불판+구이용 불판', baseQuantity: 2, unit: '개' },
      { title: '집게/가위', description: '🔥꿀팁: 스테인리스 집게+만능가위', baseQuantity: 1, unit: '세트' },
      { title: '키친타월', description: '🔥꿀팁: 기름닦기+손닦기 필수', baseQuantity: 3, unit: '롤' },
      { title: '식기/컵', description: '개인 접시+컵+수저', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '물', description: '🔥꿀팁: 식수 20L+세척용 10L', baseQuantity: 5, unit: 'L', multiplier: 1 },
      { title: '랜턴/조명', description: '🔥꿀팁: LED랜턴+스트링라이트', baseQuantity: 2, unit: '개' },
      { title: '보조배터리', description: '🔥꿀팁: 대용량 20000mAh+태양광', baseQuantity: 1, unit: '개' },
      { title: '충전케이블', description: '12V시거잭+USB충전기', baseQuantity: 1, unit: '세트' },
      { title: '휴지/물티슈', description: '🔥꿀팁: 화장지+물티슈+키친타월', baseQuantity: 3, unit: '팩' },
      { title: '쓰레기봉투', description: '🔥꿀팁: 종량제+분리수거+음식물', baseQuantity: 10, unit: '개' },
      { title: '세면도구', description: '칫솔+치약+세안용품', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '수건', description: '🔥꿀팁: 퀵드라이 타월 추천', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '슬리퍼', description: '🔥꿀팁: 편한 캠핑용 슬리퍼', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '모기향/방충제', description: '🔥꿀팁: 여름철 필수 방충용품', baseQuantity: 1, unit: '세트' },
      { title: '간편식품', description: '🔥꿀팁: 라면+통조림+즉석밥', baseQuantity: 5, unit: '개', multiplier: 1 },
      { title: '간식/음료', description: '과자+음료+술+안주', baseQuantity: 5, unit: '개', multiplier: 1 },
      { title: '응급처치용품', description: '🔥꿀팁: 상처연고+해열제+밴드', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'travel',
    name: '여행 (국내)',
    description: '🔥꿀팁 가득 국내여행 완벽 준비',
    category: '여행',
    peopleMultiplier: true,
    items: [
      { title: '여행가방', description: '🔥꿀팁: 짐 무게 24인치 추천', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '후드티+슬리퍼', description: '🔥꿀팁: 비행기/KTX 편안하게', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '옷(여벌+내의)', description: '날씨 변화 고려 +1일', baseQuantity: 3, unit: '벌', multiplier: 1 },
      { title: '세면도구', description: '샴푸+바디워시+칫솔+치약', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '수건', description: '목욕용 대형 + 세수용 소형', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '충전기+보조배터리', description: '🔥꿀팁: 여행지에서 배터리 방전', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '카메라+메모리카드', description: '📷 추억 기록 + 저장공간', baseQuantity: 1, unit: '세트' },
      { title: '간식+물', description: '맛있는 로컬푸드 + 수분보충', baseQuantity: 5, unit: '개' },
      { title: '상비약', description: '🔥꿀팁: 감기약+소화제+파스', baseQuantity: 1, unit: '세트' },
      { title: '현금+카드', description: '로컬 결제 + 비상금', baseQuantity: 100000, unit: '원' },
      { title: '여행 에코백', description: '🔥꿀팁: 기념품 구매용', baseQuantity: 1, unit: '개' },
      { title: '도시락+준비물', description: '여행지 간식 + 피크닉용', baseQuantity: 1, unit: '세트' },
      { title: '목베개', description: '🔥꿀팁: 장거리 이동 필수', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '아이마스크+귀마개', description: '🔥꿀팁: 숙면 도우미', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '여행용 슬리퍼', description: '🔥꿀팁: 숙소에서 편안하게', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '휠대용 여행가방', description: '🔥꿀팁: 백팩에 부착 가능', baseQuantity: 1, unit: '개' },
      { title: '세탁망', description: '🔥꿀팁: 더러운 옷 분리 수납', baseQuantity: 1, unit: '개' },
    ]
  },

  // === 웹 리서치 기반 신규 템플릿 ===
  {
    id: 'job_interview',
    name: '면접 준비',
    description: '💼 취업 면접 완벽 준비',
    category: '업무',
    peopleMultiplier: false,
    items: [
      { title: '이력서+자소서', description: '인쇄본 여러 부 + PDF 백업', baseQuantity: 3, unit: '부' },
      { title: '정장+넥타이', description: '🔥꿀팁: 면접 전날 다림질', baseQuantity: 1, unit: '벌' },
      { title: '구두+구두약', description: '🔥꿀팁: 깨끗한 구두는 기본', baseQuantity: 1, unit: '세트' },
      { title: '가방+폴더', description: '서류 정리용 비즈니스 가방', baseQuantity: 1, unit: '개' },
      { title: '시계+필기구', description: '시간 확인 + 메모용', baseQuantity: 1, unit: '세트' },
      { title: '신분증+필요서류', description: '주민등록초본 등 필요 서류', baseQuantity: 1, unit: '세트' },
      { title: '방향제', description: '🔥꿀팁: 너무 진하지 않게', baseQuantity: 1, unit: '개' },
      { title: '미니 티슈', description: '긴장으로 인한 땀 대비', baseQuantity: 1, unit: '개' },
      { title: '교통비+예비비', description: '버스/지하철 + 예비 차액', baseQuantity: 20000, unit: '원' },
      { title: '면접 대비 자료', description: '회사 정보 + 예상 질문 정리', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'first_date',
    name: '첫 만남 데이트',
    description: '😍 첫 인상이 중요한 데이트',
    category: '여가',
    peopleMultiplier: false,
    items: [
      { title: '데이트 의상', description: '🔥꿀팁: TPO에 맞는 깔끔한 옷차림', baseQuantity: 1, unit: '벌' },
      { title: '향수+립밤', description: '은은한 향 + 입술 관리', baseQuantity: 1, unit: '세트' },
      { title: '휴대폰 완충', description: '데이트 코스 검색 + 연락용', baseQuantity: 1, unit: '개' },
      { title: '데이트 비용', description: '🔥꿀팁: 예상보다 20% 더 준비', baseQuantity: 100000, unit: '원' },
      { title: '미니 가방', description: '지갑+핸드크림+립밤 등', baseQuantity: 1, unit: '개' },
      { title: '장소 위치', description: '만남 장소 찾기 대비 미리 확인', baseQuantity: 1, unit: '개' },
      { title: '대화 주제', description: '🔥꿀팁: 공통 관심사 5가지 준비', baseQuantity: 5, unit: '개' },
      { title: '사탕+민트', description: '식사 후 입냄새 관리', baseQuantity: 1, unit: '세트' },
      { title: '우산', description: '갑작스런 비 대비 체크', baseQuantity: 1, unit: '개' },
      { title: '추가 만남 제안', description: '🔥꿀팁: 2차 데이트 장소 미리 생각', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'remote_work',
    name: '재택근무',
    description: '🏠 집에서 효율적인 근무',
    category: '업무',
    peopleMultiplier: false,
    items: [
      { title: '외장 모니터', description: '🔥꿀팁: 듀얼 모니터로 생산성 UP', baseQuantity: 1, unit: '개' },
      { title: '어고노믹 체어', description: '장시간 앉아서 작업용', baseQuantity: 1, unit: '개' },
      { title: '블루라이트 차단 안경', description: '눈의 피로 방지', baseQuantity: 1, unit: '개' },
      { title: '노이즈 캔슬링 헤드폰', description: '🔥꿀팁: 온라인 회의 집중력', baseQuantity: 1, unit: '개' },
      { title: '데스크 램프', description: '작업 공간 조명', baseQuantity: 1, unit: '개' },
      { title: '무선 키보드/마우스', description: '자세 교정 + 무선 환경', baseQuantity: 1, unit: '세트' },
      { title: '비타민+간식', description: '집중력 유지용 건강식품', baseQuantity: 3, unit: '개' },
      { title: '다용도 충전기', description: '노트북+핸드폰 동시 충전', baseQuantity: 1, unit: '개' },
      { title: '백업 하드디스크', description: '🔥꿀팁: 중요한 작업 파일 보안', baseQuantity: 1, unit: '개' },
      { title: '컴퓨터 청소도구', description: '키보드+모니터 청소용', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'child_hospital_visit',
    name: '아이 병원 방문',
    description: '👶 아이와 병원 갈 때',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '예방접종수첩', description: '여러 병원 과거력 확인용', baseQuantity: 1, unit: '개' },
      { title: '아이 간식+음료', description: '🔥꿀팁: 대기시간 달래기용', baseQuantity: 3, unit: '개' },
      { title: '장난감+색칠도구', description: '오랜 대기시간 대비', baseQuantity: 1, unit: '세트' },
      { title: '여벌 옷+기저귀', description: '아이 옷 더러워졌을 때', baseQuantity: 1, unit: '세트' },
      { title: '소아용 마스크', description: '개인 방역 + 병원 규칙', baseQuantity: 3, unit: '개' },
      { title: '물티슈+손 소독제', description: '위생관리용', baseQuantity: 1, unit: '세트' },
      { title: '건강보험증+진료기록', description: '함께 가져가는 서류', baseQuantity: 2, unit: '개' },
      { title: '현금', description: '병원 수납 + 주차비', baseQuantity: 50000, unit: '원' },
      { title: '아이 카시트', description: '🔥꿀팁: 또르르 아이 안전', baseQuantity: 1, unit: '개' },
      { title: '이유식+분유', description: '수유 중인 아이 대비', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'elderly_care',
    name: '부모님 병원 동행',
    description: '👵 어르신과 병원 이용 시',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '의료보험증+신분증', description: '본인 및 보호자 신분증', baseQuantity: 1, unit: '세트' },
      { title: '현금+카드', description: '🔥꿀팁: 휴대용 지갑 준비', baseQuantity: 1, unit: '개' },
      { title: '다용도 쿠션', description: '딱딱한 병원 의자에 사용', baseQuantity: 1, unit: '개' },
      { title: '간편식+차', description: '오랜 대기 시간 대비', baseQuantity: 1, unit: '세트' },
      { title: '약물리스트+알레르기', description: '의사 상담용 약물 정리', baseQuantity: 1, unit: '개' },
      { title: '보행보조기+휠체어', description: '이동 불편하신 분 대비', baseQuantity: 1, unit: '세트' },
      { title: '결과지 보관폴더', description: '🔥꿀팁: 검사 결과 체계적 관리', baseQuantity: 1, unit: '개' },
      { title: '보온 담요', description: '병원 에어컨 강할 때', baseQuantity: 1, unit: '개' },
      { title: '의사 상담 메모지', description: '질문 내용 미리 준비', baseQuantity: 1, unit: '개' },
      { title: '비상연락망', description: '가족 연락처 리스트', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'study_abroad_prep',
    name: '어학연수 준비',
    description: '해외 단기 어학연수 준비',
    category: '공부',
    peopleMultiplier: false,
    items: [
      { title: '여권+비자', description: '유효기간 6개월 이상 + 비자 신청', baseQuantity: 1, unit: '세트' },
      { title: '영문 서류', description: '학력증명서+은행잔고증명서', baseQuantity: 1, unit: '세트' },
      { title: '해외용 전원코드', description: '🔥꿀팁: 한국 전자제품 사용용', baseQuantity: 1, unit: '개' },
      { title: '상비약+비상약', description: '감기약+소화제+해열제', baseQuantity: 1, unit: '세트' },
      { title: '현지 화폐+신용카드', description: '환전+달러+해외결제용 카드', baseQuantity: 1, unit: '세트' },
      { title: '의류+내의', description: '현지 기후에 맞는 옷 준비', baseQuantity: 7, unit: '벌' },
      { title: '영한사전+공부서적', description: '어학연수용 교재', baseQuantity: 3, unit: '권' },
      { title: '항공여행자보험', description: '🔥꿀팁: 의료비 취소비 보장', baseQuantity: 1, unit: '건' },
      { title: '데이터 로밍', description: '현지 인터넷 이용 대비', baseQuantity: 1, unit: '건' },
      { title: '한국 선물', description: '호스트가정+교사 선물용', baseQuantity: 5, unit: '개' },
    ]
  },
  {
    id: 'home_maintenance',
    name: '집 수리/정비',
    description: '🔨 집안 간단한 수리용품',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '멀티 드라이버', description: '다양한 나사 조이기 가능', baseQuantity: 1, unit: '개' },
      { title: '전동드릴+비트', description: '🔥꿀팁: 벽 나사고정용 필수', baseQuantity: 1, unit: '세트' },
      { title: '방수테이프', description: '물새는 곳 임시처리', baseQuantity: 1, unit: '개' },
      { title: '전선커터+전기테이프', description: '전기 관련 작업용', baseQuantity: 1, unit: '세트' },
      { title: '연장코드+멀티탭', description: '전원 부족할 때 대비', baseQuantity: 1, unit: '세트' },
      { title: '배수구 청소도구', description: '드렌처+호스 이용 뚫기', baseQuantity: 1, unit: '세트' },
      { title: '앵커+나사세트', description: '벽에 걸기/고정 공구', baseQuantity: 1, unit: '세트' },
      { title: '수평계', description: '🔥꿀팁: 틀어지지 않게 수평 확인', baseQuantity: 1, unit: '개' },
      { title: '순간접착제+실리콘', description: '빠른 고정 또는 밀폐용', baseQuantity: 1, unit: '세트' },
      { title: '안전장비', description: '장갑+보안경+헤드랜턴', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'moving',
    name: '이사 준비',
    description: '🏠 완벽한 이사를 위한 필수 체크리스트',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '이사업체 예약', description: '🔥꿀팁: 3곳 이상 견적 비교', baseQuantity: 1, unit: '개' },
      { title: '포장박스+테이프', description: '🔥꿀팁: 다양한 크기+투명테이프', baseQuantity: 30, unit: '개' },
      { title: '뽁뽁이+신문지', description: '🔥꿀팁: 깨지기 쉬운 물건 포장', baseQuantity: 10, unit: '롤' },
      { title: '유성펜+라벨지', description: '🔥꿀팁: 박스별 내용물 표시', baseQuantity: 5, unit: '개' },
      { title: '이사 전 청소용품', description: '🔥꿀팁: 락스+걸레+청소기', baseQuantity: 1, unit: '세트' },
      { title: '주소변경 서류', description: '🔥꿀팁: 주민등록+운전면허+건강보험', baseQuantity: 1, unit: '세트' },
      { title: '은행/카드사 주소변경', description: '🔥꿀팁: 인터넷뱅킹으로 미리', baseQuantity: 5, unit: '곳' },
      { title: '인터넷/케이블TV 이전', description: '🔥꿀팁: 2주 전 미리 신청', baseQuantity: 1, unit: '세트' },
      { title: '전기/가스/수도 신청', description: '🔥꿀팁: 입주 전날까지 개통', baseQuantity: 1, unit: '세트' },
      { title: '택배/우편물 주소변경', description: '🔥꿀팁: 우체국 주소변경서비스', baseQuantity: 1, unit: '개' },
      { title: '냉장고 정리', description: '🔥꿀팁: 이사 3일 전부터 음식정리', baseQuantity: 1, unit: '개' },
      { title: '귀중품 따로 보관', description: '🔥꿀팁: 현금+통장+인감+귀금속', baseQuantity: 1, unit: '세트' },
      { title: '응급처치 키트', description: '🔥꿀팁: 반창고+소독약+진통제', baseQuantity: 1, unit: '세트' },
      { title: '간단한 식사준비', description: '🔥꿀팁: 컵라면+김밥+음료', baseQuantity: 5, unit: '개' },
      { title: '새 집 열쇠+보안', description: '🔥꿀팁: 디지털도어락 비번변경', baseQuantity: 1, unit: '세트' },
      { title: '이사 후 정리용품', description: '🔥꿀팁: 행거+정리함+청소도구', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'overseas_travel',
    name: '해외여행',
    description: '✈️ 해외여행 필수 준비물 완벽 가이드',
    category: '여행',
    peopleMultiplier: true,
    items: [
      { title: '여권+비자', description: '🔥꿀팁: 유효기간 6개월 이상 확인', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '항공권+숙소예약', description: '🔥꿀팁: 모바일앱+출력본 둘 다', baseQuantity: 1, unit: '세트' },
      { title: '여행자보험', description: '🔥꿀팁: 의료비+항공기지연 보장', baseQuantity: 1, unit: '개' },
      { title: '해외용 신용카드', description: '🔥꿀팁: VISA/Master 2장 이상', baseQuantity: 2, unit: '개' },
      { title: '외화환전', description: '🔥꿀팁: 소액권 위주로 환전', baseQuantity: 500, unit: '달러' },
      { title: '국제운전면허증', description: '🔥꿀팁: 렌터카 이용 시 필수', baseQuantity: 1, unit: '개' },
      { title: '해외용 심카드', description: '🔥꿀팁: 공항에서 구매 또는 사전주문', baseQuantity: 1, unit: '개' },
      { title: '멀티어댑터', description: '🔥꿀팁: 국가별 플러그 확인', baseQuantity: 1, unit: '개' },
      { title: '보조배터리', description: '🔥꿀팁: 20000mAh 이상 기내반입', baseQuantity: 1, unit: '개' },
      { title: '여행용 캐리어', description: '🔥꿀팁: 기내용 20인치+위탁용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '상비약', description: '🔥꿀팁: 개인처방전+감기약+소화제', baseQuantity: 1, unit: '세트' },
      { title: '옷(기후별)', description: '🔥꿀팁: 현지 날씨 확인+레이어링', baseQuantity: 7, unit: '벌', multiplier: 1 },
      { title: '세면용품', description: '🔥꿀팁: 100ml 이하 용기로 소분', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '선글라스+선크림', description: '🔥꿀팁: SPF50 이상 자외선차단', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '번역앱+지도앱', description: '🔥꿀팁: 구글번역+지도 오프라인 다운', baseQuantity: 1, unit: '세트' },
      { title: '비상연락처 메모', description: '🔥꿀팁: 대사관+보험사+가족 연락처', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'wedding_guest',
    name: '결혼식 하객 준비',
    description: '💒 결혼식 참석을 위한 완벽 준비',
    category: '여가',
    peopleMultiplier: false,
    items: [
      { title: '축의금 준비', description: '🔥꿀팁: 새 지폐로 축의금봉투에', baseQuantity: 1, unit: '개' },
      { title: '정장/한복', description: '🔥꿀팁: 신랑신부보다 화려하지 않게', baseQuantity: 1, unit: '벌' },
      { title: '구두+양말', description: '🔥꿀팁: 편한 구두+여분양말', baseQuantity: 1, unit: '세트' },
      { title: '핸드백/클러치', description: '🔥꿀팁: 작은 가방+필수품만', baseQuantity: 1, unit: '개' },
      { title: '액세서리', description: '🔥꿀팁: 과하지 않은 정도의 장신구', baseQuantity: 1, unit: '세트' },
      { title: '화장품/헤어용품', description: '🔥꿀팁: 터치업용 화장품+헤어스프레이', baseQuantity: 1, unit: '세트' },
      { title: '카메라/스마트폰', description: '🔥꿀팁: 충전 완료+보조배터리', baseQuantity: 1, unit: '개' },
      { title: '축하 메시지 준비', description: '🔥꿀팁: 진심이 담긴 축하인사 미리', baseQuantity: 1, unit: '개' },
      { title: '하객명부 확인', description: '🔥꿀팁: 신랑신부측 구분 확인', baseQuantity: 1, unit: '개' },
      { title: '교통편 준비', description: '🔥꿀팁: 대중교통 또는 대리운전', baseQuantity: 1, unit: '개' },
      { title: '여분 스타킹/양말', description: '🔥꿀팁: 뜯어지거나 더러워질 때 대비', baseQuantity: 1, unit: '개' },
      { title: '손수건/티슈', description: '🔥꿀팁: 감동의 눈물 대비', baseQuantity: 1, unit: '개' },
    ]
  },

  // === 신규 실용 템플릿 ===
  {
    id: 'funeral_visit',
    name: '장례식/조문',
    description: '🙏 장례식장 조문 시 필요한 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '조의금(흰봉투)', description: '새 지폐보다 구권 사용 권장', baseQuantity: 1, unit: '개' },
      { title: '검은 정장/한복', description: '단정한 검은색 복장', baseQuantity: 1, unit: '벌' },
      { title: '검은 구두', description: '광을 낸 검은 구두', baseQuantity: 1, unit: '켤레' },
      { title: '검은 넥타이', description: '남성 필수 검은 넥타이', baseQuantity: 1, unit: '개' },
      { title: '검은 양말', description: '흰 양말 착용 금지', baseQuantity: 1, unit: '켤레' },
      { title: '흰 와이셔츠', description: '검은 정장 안에 입을 흰 셔츠', baseQuantity: 1, unit: '벌' },
      { title: '핸드폰(무음)', description: '장례식장 내 무음 필수', baseQuantity: 1, unit: '개' },
      { title: '교통비', description: '장례식장 왕복 교통비', baseQuantity: 20000, unit: '원' },
      { title: '현금(식사비)', description: '장례식장 식사 비용', baseQuantity: 10000, unit: '원' },
      { title: '손수건', description: '예의 바른 조문 예절용', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'waterpark',
    name: '워터파크',
    description: '💦 신나는 워터파크 물놀이 준비물',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '입장권', description: '미리 온라인 예매 시 할인', baseQuantity: 1, unit: '매', multiplier: 1 },
      { title: '수영복', description: '물놀이용 수영복', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '래시가드', description: '자외선 차단 + 체온 유지', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '비치타월', description: '물기 제거용 큰 타월', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '선크림(SPF50+방수)', description: '방수 기능 필수, 2시간마다 재도포', baseQuantity: 1, unit: '개' },
      { title: '방수폰케이스', description: '핸드폰 물 손상 방지', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '아쿠아슈즈', description: '미끄럼 방지 물놀이 신발', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '수경', description: '물속 시야 확보용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '튜브/구명조끼', description: '수영 미숙자 안전용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '간식비/식사비', description: '워터파크 내 식당 비용', baseQuantity: 30000, unit: '원', multiplier: 1 },
      { title: '여분옷', description: '물놀이 후 갈아입을 옷', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '비닐봉투(젖은옷)', description: '젖은 수영복 분리 보관', baseQuantity: 2, unit: '개' },
      { title: '로션', description: '물놀이 후 피부 보습', baseQuantity: 1, unit: '개' },
      { title: '귀마개', description: '귓속 물 방지용', baseQuantity: 1, unit: '개', multiplier: 1 },
    ]
  },
  {
    id: 'airport_departure',
    name: '공항 출국',
    description: '✈️ 해외 출국 공항 체크리스트',
    category: '여행',
    peopleMultiplier: false,
    items: [
      { title: '여권', description: '유효기간 6개월 이상 필수 확인', baseQuantity: 1, unit: '개' },
      { title: '항공권(모바일/인쇄)', description: '모바일 탑승권 또는 출력본', baseQuantity: 1, unit: '매' },
      { title: '비자(필요시)', description: '방문 국가 비자 요구사항 확인', baseQuantity: 1, unit: '개' },
      { title: '해외용신용카드', description: 'VISA/Master 해외 결제 카드', baseQuantity: 2, unit: '개' },
      { title: '외화', description: '현지 화폐 또는 달러 환전', baseQuantity: 1, unit: '세트' },
      { title: '보조배터리(기내반입)', description: '100Wh 이하만 기내 반입 가능', baseQuantity: 1, unit: '개' },
      { title: '여행자보험증서', description: '의료비+항공지연 보장 확인', baseQuantity: 1, unit: '개' },
      { title: '액체류지퍼백(100ml이하)', description: '기내 반입 액체류 규정 준수', baseQuantity: 1, unit: '개' },
      { title: '목베개', description: '장거리 비행 목 보호용', baseQuantity: 1, unit: '개' },
      { title: '이어폰/헤드폰', description: '기내 엔터테인먼트 및 소음 차단', baseQuantity: 1, unit: '개' },
      { title: '기내용간식', description: '기내식 외 추가 간식', baseQuantity: 3, unit: '개' },
      { title: '펜(입국서류작성용)', description: '비행 중 입국신고서 작성용', baseQuantity: 1, unit: '개' },
      { title: '면세품주문확인서', description: '사전 면세 주문 시 출력 필요', baseQuantity: 1, unit: '개' },
      { title: '해외유심/이심', description: '현지 데이터 이용을 위한 유심', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'drivers_license_test',
    name: '운전면허 시험',
    description: '🚗 운전면허 시험 당일 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '신분증', description: '주민등록증 또는 여권', baseQuantity: 1, unit: '개' },
      { title: '수험표/접수증', description: '시험 접수 확인서 출력', baseQuantity: 1, unit: '매' },
      { title: '안경(필요시)', description: '시력 교정이 필요한 경우 지참', baseQuantity: 1, unit: '개' },
      { title: '편한옷', description: '운전에 방해되지 않는 복장', baseQuantity: 1, unit: '벌' },
      { title: '편한신발(운전용)', description: '굽 없는 편안한 신발 필수', baseQuantity: 1, unit: '켤레' },
      { title: '필기구', description: '필기시험용 볼펜 또는 연필', baseQuantity: 2, unit: '개' },
      { title: '물/음료', description: '시험 대기 중 수분 보충', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '긴 대기시간 대비 간단한 간식', baseQuantity: 2, unit: '개' },
      { title: '교통비', description: '면허시험장 왕복 교통비', baseQuantity: 20000, unit: '원' },
      { title: '면허학원교재', description: '대기 중 최종 복습용', baseQuantity: 1, unit: '권' },
      { title: '현금(수수료)', description: '시험 응시료 및 발급 수수료', baseQuantity: 20000, unit: '원' },
    ]
  },
  {
    id: 'glamping',
    name: '글램핑',
    description: '⛺ 편안한 글램핑 준비물',
    category: '아웃도어',
    peopleMultiplier: true,
    items: [
      { title: '예약확인서', description: '글램핑 예약 확인서 출력 또는 모바일', baseQuantity: 1, unit: '개' },
      { title: '편한옷(여벌)', description: '활동하기 편한 캐주얼 의상', baseQuantity: 2, unit: '벌', multiplier: 1 },
      { title: '잠옷', description: '글램핑 텐트 내 편안한 잠옷', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '슬리퍼', description: '텐트 안팎에서 신을 슬리퍼', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '세면도구', description: '칫솔, 치약, 폼클렌징 등', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '수건', description: '개인 수건', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '보조배터리', description: '야외에서 핸드폰 충전용', baseQuantity: 1, unit: '개' },
      { title: '블루투스스피커', description: '캠핑 분위기 음악용', baseQuantity: 1, unit: '개' },
      { title: '간식/음료', description: '텐트에서 먹을 간식과 음료', baseQuantity: 5, unit: '개', multiplier: 1 },
      { title: '고기/식재료', description: '바비큐용 고기와 채소 (1인당 200g)', baseQuantity: 200, unit: 'g', multiplier: 1 },
      { title: '숯/착화제(직접구이시)', description: '직화 바비큐 시 필요', baseQuantity: 1, unit: '세트' },
      { title: '보드게임/카드', description: '밤에 즐길 실내 게임', baseQuantity: 1, unit: '세트' },
      { title: '방충제', description: '야외 모기 및 벌레 퇴치용', baseQuantity: 1, unit: '개' },
      { title: '손전등/랜턴', description: '야간 이동 시 조명', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'seollal_homecoming',
    name: '설날/명절 귀성',
    description: '🎋 설날 고향 방문 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '부모님선물세트', description: '건강식품, 과일, 한과 등 선물', baseQuantity: 1, unit: '세트' },
      { title: '세뱃돈(새지폐)', description: '은행에서 미리 새 지폐로 교환', baseQuantity: 1, unit: '세트' },
      { title: '세뱃돈봉투', description: '명절 전용 예쁜 봉투 준비', baseQuantity: 5, unit: '개' },
      { title: '편한옷+한복', description: '명절 인사용 한복 또는 단정한 옷', baseQuantity: 1, unit: '벌' },
      { title: '귀성길간식', description: '장거리 이동 중 먹을 간식', baseQuantity: 5, unit: '개' },
      { title: '귀성길음료', description: '장거리 이동 중 음료', baseQuantity: 3, unit: '개' },
      { title: '핸드폰충전기', description: '장거리 이동 및 귀성길 사용', baseQuantity: 1, unit: '개' },
      { title: '보조배터리', description: '이동 중 핸드폰 배터리 대비', baseQuantity: 1, unit: '개' },
      { title: '운전면허증', description: '자가 운전 귀성 시 필수', baseQuantity: 1, unit: '개' },
      { title: '하이패스카드', description: '고속도로 톨게이트 통과용', baseQuantity: 1, unit: '개' },
      { title: '비상약', description: '멀미약, 소화제, 두통약', baseQuantity: 1, unit: '세트' },
      { title: '여분옷', description: '1박 이상 체류 시 갈아입을 옷', baseQuantity: 2, unit: '벌' },
    ]
  },
  {
    id: 'hospital_visit',
    name: '병문안',
    description: '🌷 입원 환자 병문안 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '문병선물(과일바구니/영양식)', description: '환자 식이제한 사전 확인 필수', baseQuantity: 1, unit: '개' },
      { title: '화환/꽃(선택)', description: '병원 내 반입 가능 여부 확인', baseQuantity: 1, unit: '개' },
      { title: '현금(주차비)', description: '병원 주차 요금 대비', baseQuantity: 10000, unit: '원' },
      { title: '마스크', description: '병원 내 감염 예방 필수', baseQuantity: 2, unit: '개' },
      { title: '손소독제', description: '병실 입실 전후 손 위생', baseQuantity: 1, unit: '개' },
      { title: '편한신발', description: '병원 복도 이동에 편한 신발', baseQuantity: 1, unit: '켤레' },
      { title: '핸드폰(무음)', description: '병실 내 무음 또는 진동 설정', baseQuantity: 1, unit: '개' },
      { title: '주차카드/교통카드', description: '대중교통 또는 주차 정산용', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'pet_hospital',
    name: '반려동물 병원',
    description: '🐾 반려동물 동물병원 방문 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '반려동물등록증', description: '동물등록 번호 확인용', baseQuantity: 1, unit: '개' },
      { title: '진료기록/접종수첩', description: '이전 진료 내역 및 예방접종 기록', baseQuantity: 1, unit: '개' },
      { title: '이동장/캐리어', description: '안전한 이동을 위한 케이지', baseQuantity: 1, unit: '개' },
      { title: '목줄/하네스', description: '대기실에서의 안전 관리', baseQuantity: 1, unit: '개' },
      { title: '배변봉투/패드', description: '이동 중 또는 대기 중 배변 처리', baseQuantity: 5, unit: '개' },
      { title: '간식(진정용)', description: '긴장한 반려동물 달래기용', baseQuantity: 3, unit: '개' },
      { title: '물+물그릇', description: '대기 중 수분 보충', baseQuantity: 1, unit: '세트' },
      { title: '담요(불안시)', description: '익숙한 냄새로 안정감 제공', baseQuantity: 1, unit: '개' },
      { title: '현금/카드(진료비)', description: '진료비 결제 수단', baseQuantity: 1, unit: '개' },
      { title: '보험서류(해당시)', description: '펫보험 가입 시 청구 서류', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'yoga_pilates',
    name: '요가/필라테스',
    description: '🧘 요가 및 필라테스 수업 준비물',
    category: '운동',
    peopleMultiplier: false,
    items: [
      { title: '요가매트', description: '개인 매트 (두께 6mm 이상 권장)', baseQuantity: 1, unit: '개' },
      { title: '운동복(스트레칭용)', description: '신축성 좋은 요가복/레깅스', baseQuantity: 1, unit: '벌' },
      { title: '수건(소형)', description: '운동 중 땀 닦기용', baseQuantity: 1, unit: '개' },
      { title: '물병', description: '수분 보충용 텀블러', baseQuantity: 1, unit: '개' },
      { title: '요가블록(필요시)', description: '자세 보조용 블록', baseQuantity: 2, unit: '개' },
      { title: '스트랩(필요시)', description: '유연성 부족 시 보조 도구', baseQuantity: 1, unit: '개' },
      { title: '양말(미끄럼방지)', description: '필라테스 수업 시 그립 양말 필수', baseQuantity: 1, unit: '켤레' },
      { title: '헤어밴드/머리끈', description: '운동 중 머리카락 정리', baseQuantity: 2, unit: '개' },
      { title: '세면도구(샤워시)', description: '수업 후 샤워 시 개인 세면용품', baseQuantity: 1, unit: '세트' },
      { title: '회원카드', description: '센터 출입 및 수강권 확인', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'road_trip',
    name: '장거리 드라이브',
    description: '🚙 장거리 자동차 여행 준비물',
    category: '여행',
    peopleMultiplier: true,
    items: [
      { title: '운전면허증', description: '운전 시 필수 지참', baseQuantity: 1, unit: '개' },
      { title: '차량등록증사본', description: '차량 서류 분실 대비 사본', baseQuantity: 1, unit: '개' },
      { title: '하이패스카드', description: '고속도로 통행료 자동 결제', baseQuantity: 1, unit: '개' },
      { title: '차량용충전기', description: '시거잭 또는 USB 차량 충전기', baseQuantity: 1, unit: '개' },
      { title: '간식/음료', description: '장거리 이동 중 에너지 보충', baseQuantity: 5, unit: '개', multiplier: 1 },
      { title: '졸음방지껌/커피', description: '졸음 운전 예방 필수', baseQuantity: 3, unit: '개' },
      { title: '선글라스', description: '역광 및 눈부심 방지', baseQuantity: 1, unit: '개' },
      { title: '차량용방향제', description: '장시간 차 안 공기 관리', baseQuantity: 1, unit: '개' },
      { title: '비상삼각대', description: '차량 고장/사고 시 후방 경고', baseQuantity: 1, unit: '개' },
      { title: '점프케이블', description: '배터리 방전 시 긴급 대처', baseQuantity: 1, unit: '개' },
      { title: '현금(톨게이트/주유)', description: '하이패스 불가 구간 및 주유비', baseQuantity: 50000, unit: '원' },
      { title: '차량용쿠션', description: '장거리 허리 통증 예방', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '음악플레이리스트', description: '드라이브 분위기 음악 미리 준비', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'graduation_ceremony',
    name: '졸업식',
    description: '🎓 졸업식 당일 준비물',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '학사모+학위복(대여확인)', description: '학교 대여 일정 및 사이즈 사전 확인', baseQuantity: 1, unit: '세트' },
      { title: '정장/드레스', description: '학위복 안에 입을 단정한 의상', baseQuantity: 1, unit: '벌' },
      { title: '구두', description: '정장에 어울리는 구두', baseQuantity: 1, unit: '켤레' },
      { title: '카메라/핸드폰', description: '졸업 기념 사진 촬영용', baseQuantity: 1, unit: '개' },
      { title: '보조배터리', description: '사진 많이 찍을 때 배터리 대비', baseQuantity: 1, unit: '개' },
      { title: '꽃다발(가족용)', description: '가족이 준비하는 축하 꽃다발', baseQuantity: 1, unit: '개' },
      { title: '현금(식사비)', description: '졸업 후 가족 식사 비용', baseQuantity: 100000, unit: '원' },
      { title: '졸업앨범비', description: '졸업앨범 수령 및 추가 구매비', baseQuantity: 1, unit: '개' },
      { title: '감사편지(은사님)', description: '담임/교수님께 드릴 감사 편지', baseQuantity: 1, unit: '개' },
      { title: '핸드크림/립밤', description: '사진 촬영 전 피부 관리', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'christmas_party',
    name: '크리스마스 파티',
    description: '🎄 크리스마스 홈 파티 준비물',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '선물(교환용)', description: '금액 한도 정해서 준비하는 교환 선물', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '파티음식', description: '치킨, 피자 등 파티 음식', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '음료/와인', description: '파티 분위기에 맞는 음료', baseQuantity: 2, unit: '병', multiplier: 1 },
      { title: '크리스마스장식', description: '트리, 전구, 리스 등 분위기 장식', baseQuantity: 1, unit: '세트' },
      { title: '케이크', description: '크리스마스 케이크 사전 예약 추천', baseQuantity: 1, unit: '개' },
      { title: '파티모자/소품', description: '산타모자, 뿔 머리띠 등', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '블루투스스피커', description: '크리스마스 캐럴 재생용', baseQuantity: 1, unit: '개' },
      { title: '보드게임/카드게임', description: '파티 여흥용 게임', baseQuantity: 2, unit: '개' },
      { title: '카메라(추억촬영)', description: '파티 순간 기록용', baseQuantity: 1, unit: '개' },
      { title: '일회용접시/컵', description: '뒷정리 편한 일회용 식기', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '쓰레기봉투', description: '파티 후 정리용 대형 봉투', baseQuantity: 3, unit: '개' },
    ]
  }
];

export function getTemplate(templateId: string): SituationTemplate | undefined {
  return SITUATION_TEMPLATES.find(template => template.id === templateId);
}

export function calculateQuantity(item: { baseQuantity?: number; multiplier?: number }, peopleCount: number = 1): number {
  if (item.multiplier === undefined || item.multiplier === null) return item.baseQuantity || 1;
  return (item.baseQuantity || 1) * (item.multiplier || 1) * Math.max(1, peopleCount);
}